import eslintPluginAstro from 'eslint-plugin-astro';
import simpleImportSort from 'eslint-plugin-simple-import-sort';
import tseslint from 'typescript-eslint';

export default [
	{
		ignores: [
			'dist/**',
			'.astro/**',
			'.sst/**',
			// Generated by `npm run typegen`
			'src/sanity.types.ts',
		],
	},
	...tseslint.configs.recommended,
	...eslintPluginAstro.configs.recommended,
	{
		files: ['**/*.{js,mjs,ts,astro}'],
		plugins: {
			'simple-import-sort': simpleImportSort,
		},
		rules: {
			'simple-import-sort/imports': 'warn',
			'simple-import-sort/exports': 'warn',
			'@typescript-eslint/no-unused-vars': [
				'warn',
				{ argsIgnorePattern: '^_', varsIgnorePattern: '^(_|Props)$' },
			],
		},
	},
	{
		// SST's own convention for loading its generated platform types.
		files: ['sst.config.ts'],
		rules: {
			'@typescript-eslint/triple-slash-reference': 'off',
		},
	},
];
