title: Maestro
description: >-
  Maestro connects every part of your performing arts organization, simplifying
  ticketing, patron relationships, memberships, fundraising, and reporting.
navigation:
  - label: Product
    href: '#product'
  - label: Features
    href: '#features'
  - label: Integrations
    href: '#integrations'
  - label: Roadmap
    href: '#roadmap'
  - label: About
    href: '#about'
login:
  label: Log in
  href: '#'
headerCta:
  label: Request demo
  href: '#demo'
footer:
  tagline: Simplify everything behind the scenes.
  image: /src/assets/cms/site/footer/image.png
  social:
    - label: LinkedIn
      href: '#'
    - label: X/Twitter
      href: '#'
    - label: Instagram
      href: '#'
  copyright: © 2026 Maestro, Inc. All rights reserved.
  credit:
    label: By Fictive Kin
    href: https://fictivekin.com
